backend:
  name: github
  repo: bhattaraimadhu56/Madhu-Portfolio
  branch: main
  auth_scope: repo
  client_id: Ov23liupDQLR8p2DroSY
  client_secret: 2df320e3570067b6cea521b06f686db1545fcc4b
  base_url: https://www.madhudata.com/admin/

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test Content"
    folder: "content/test"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
